#!/bin/bash
x=$(hyprctl -j monitors | jq '.[1].x')
echo $x
if [ $x -ne 4072 ]
then
    echo "Hi"
    hyprctl keyword monitor DP-3, 3840x2160, 4072x0, 1.25
else
    echo "Bye"
    hyprctl keyword monitor DP-3, 3840x2160, 3072x0, 1.25
fi
